apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: whg50mkok-nodejs-gitops
  description: This is GitOps manifest for whg50mkok-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: whg50mkok-nodejs
    janus-idp.io/tekton: whg50mkok-nodejs 
    backstage.io/kubernetes-id: whg50mkok-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:whg50mkok-nodejs
