apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: whg50mkok-nodejs
  janus-idp.io/tekton: whg50mkok-nodejs
  backstage.io/kubernetes-id: whg50mkok-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: whg50mkok-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
