apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: whg50mkok-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: whg50mkok-nodejs 
  name: whg50mkok-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: whg50mkok-nodejs 
